### ISSUE TITLE
Remove MLJBase, DataFrames, as hard dependencies

### ISSUE THREAD

**Issue by ablaom** [ml-unito/PartitionedLS#5]
It should be possible to arrange that MLJBase is only a *test* dependency, by only calling `MLJModelInterface` methods outside of tests. 

I'd also look to see if DataFrames is really necessary. Generally ML packages add Tables.jl dependency and write code in a Tables-generic way. Of course DataFrames can be a test dependency as well, for convenience.

**Comment by boborbt** [comment]
Fixed in #3 6b9a3f7
