### ISSUE TITLE
Consider more generic methods to allow float types other than Float64

### ISSUE THREAD

**Issue by ablaom** [ml-unito/PartitionedLS#6]
It looks like some PartitionedLS code is not written in a generic style, which precludes the use of non-Float64 data. See for example [here](https://github.com/ml-unito/PartitionedLS.jl/blob/6b9a3f7ceea6a43b057a4f9053b3f0cefd6afaff/src/PartitionedLSAlt.jl#L48). This could preclude running code efficiently on a GPU, for example, which requires `Float32`. Also, auto-diff using ForwardDiff.jl would be precluded (functions must allow `Real` scalars). 

Are the restrictive type annotations here necessary? For example, could `AbstractVector{Float64}` just as well be `AbstractVector{<:AbstractFloat}` or `AbstractFloat{<:Real}` or even left unannotated? 

It is true that type annotations in structs help performance. Type annotations in functions usually have no performance benefit, as the compiler creates a compiled method specialised  to each type called on. It's my impression that type annotations are chiefly used in methods for dispatch (ie, to distinguish two methods of the same function) and, to a lesser degree, as guards against calling on data which will silently lead to  wrong behaviour.

**Comment by boborbt** [comment]
Thanks for the suggestion. I switched to AbstractFloat everywhere in commit [b1ebd22](https://github.com/ml-unito/PartitionedLS.jl/commit/b1ebd22e5675fc6fdc450ce2b7019b0cdf6d1ea5)
