### ISSUE TITLE
Add TagBot and  CompatHelper actions

### ISSUE THREAD

**Issue by ablaom** [ml-unito/PartitionedLS#8]
These are very helpful additions for Julia pkg maintenance.

https://github.com/JuliaRegistries/TagBot : tag new releases automatically

https://github.com/JuliaRegistries/CompatHelper.jl: automatically generate PR's when dependencies break existing compat bounds

You may also take a look at [PkgTemplates.jl](https://github.com/JuliaCI/PkgTemplates.jl) for other ideas; see in particular [this](https://github.com/JuliaCI/PkgTemplates.jl/tree/master/.github/workflows).

**Comment by boborbt** [comment]
Latest commit adds TAgBot and CompatHelper. I had a look at the references you gave me, but CI seems to add little to what already is in place (if I'm not mistaken adds actions for tests and doc generation, which I already have).

If you do not have any other specific requirements I would considered closed this issue.
