### ISSUE TITLE
Typos in doc string

### ISSUE THREAD

**Issue by ablaom** [ml-unito/PartitionedLS#9]
You can see [here](https://alan-turing-institute.github.io/MLJ.jl/dev/models/PartLS_PartitionedLS/) a couple of typos:

- "interafacew" -> "interface"
- There is no entry for `y` under "Training data". See my original suggestion [here](https://github.com/JuliaAI/MLJModels.jl/issues/552#issuecomment-2046058014).

**Comment by boborbt** [comment]
Thank you for the suggestion. I fixed this in the latest commit where I also merged the work for supporting precompile tools (I followed your suggestion and only supported precompilation for the native interface).
